"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 oldcar.gltf 
Author: wallon (https://sketchfab.com/realwallon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-car-09431a8df4344a84aa83a4095bef10fc
Title: Cartoon Car
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Oldcar(props) {
  const { nodes, materials } = useGLTF('/oldcarold/oldcar.gltf')
  const oldcarRef=useRef();
  useFrame(()=>{
    if(oldcarRef.current)
    oldcarRef.current.rotation.y+=0.015;
  if(oldcarRef.current.position.y>-1)
  oldcarRef.current.position.y-=0.1;
  })
  return (
    <group {...props} ref={oldcarRef} position={[0,4,0]} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.black_floats_Pure_black_0.geometry} material={materials.Pure_black} />
          <mesh geometry={nodes.black_floats_chrome_0.geometry} material={materials.chrome} />
        </group>
        <mesh geometry={nodes.body_car_body_0.geometry} material={materials.car_body} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.hood_car_body_0.geometry} material={materials.car_body} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.front_bumper_carbon_fiber_0.geometry} material={materials.carbon_fiber} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.front_fenders_carbon_fiber_0.geometry} material={materials.carbon_fiber} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane006_car_body_0.geometry} material={materials.car_body} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane008_window_0.geometry} material={materials.window} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane009_black_parts_0.geometry} material={materials.black_parts} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane007_black_parts_0.geometry} material={materials.black_parts} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.trunk_car_body_0.geometry} material={materials.car_body} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.black_parts_black_parts_0.geometry} material={materials.black_parts} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.rear_fenders_carbon_fiber_0.geometry} material={materials.carbon_fiber} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.headlight_glass_headlight_glass_0.geometry} material={materials.headlight_glass} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane026_chrome_0.geometry} material={materials.chrome} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.rear_bumper_carbon_fiber_0.geometry} material={materials.carbon_fiber} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.exhaust_chrome_0.geometry} material={materials.chrome} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane005_black_parts_0.geometry} material={materials.black_parts} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.side_skirts_carbon_fiber_0.geometry} material={materials.carbon_fiber} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane011_window_0.geometry} material={materials.window} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane014_black_parts_0.geometry} material={materials.black_parts} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane017_window_0.geometry} material={materials.window} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane033_black_parts_0.geometry} material={materials.black_parts} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane034_black_parts_0.geometry} material={materials.black_parts} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane035_window_0.geometry} material={materials.window} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane036_black_parts_0.geometry} material={materials.black_parts} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.mirrors_chrome_0.geometry} material={materials.chrome} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.front_right_wheel_wheel_0.geometry} material={materials.wheel} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane038_black_parts_0.geometry} material={materials.black_parts} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.intercooler_intercooler_0.geometry} material={materials.intercooler} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.rear_wheels_wheel_0.geometry} material={materials.wheel} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.front_left_wheel_wheel_0.geometry} material={materials.wheel} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/oldcar.gltf')
